#!/usr/bin/env node
/**
 * Build script: generates webview/vendor/highlight.bundle.js
 * Creates a self-contained browser-compatible bundle that exposes window.hljs.
 * Includes only the languages most relevant for coding assistants.
 */

const hljs = require('highlight.js/lib/core');

// Register the languages we care about for a coding assistant
const LANGS = [
    ['javascript', require('highlight.js/lib/languages/javascript')],
    ['typescript', require('highlight.js/lib/languages/typescript')],
    ['python',     require('highlight.js/lib/languages/python')],
    ['rust',       require('highlight.js/lib/languages/rust')],
    ['go',         require('highlight.js/lib/languages/go')],
    ['java',       require('highlight.js/lib/languages/java')],
    ['kotlin',     require('highlight.js/lib/languages/kotlin')],
    ['swift',      require('highlight.js/lib/languages/swift')],
    ['csharp',     require('highlight.js/lib/languages/csharp')],
    ['cpp',        require('highlight.js/lib/languages/cpp')],
    ['c',          require('highlight.js/lib/languages/c')],
    ['php',        require('highlight.js/lib/languages/php')],
    ['ruby',       require('highlight.js/lib/languages/ruby')],
    ['bash',       require('highlight.js/lib/languages/bash')],
    ['shell',      require('highlight.js/lib/languages/shell')],
    ['css',        require('highlight.js/lib/languages/css')],
    ['scss',       require('highlight.js/lib/languages/scss')],
    ['html',       require('highlight.js/lib/languages/xml')],   // hljs calls HTML "xml"
    ['xml',        require('highlight.js/lib/languages/xml')],
    ['json',       require('highlight.js/lib/languages/json')],
    ['yaml',       require('highlight.js/lib/languages/yaml')],
    ['toml',       require('highlight.js/lib/languages/ini')],   // closest match
    ['sql',        require('highlight.js/lib/languages/sql')],
    ['markdown',   require('highlight.js/lib/languages/markdown')],
    ['dockerfile', require('highlight.js/lib/languages/dockerfile')],
    ['makefile',   require('highlight.js/lib/languages/makefile')],
    ['diff',       require('highlight.js/lib/languages/diff')],
    ['plaintext',  require('highlight.js/lib/languages/plaintext')],
];

for (const [name, def] of LANGS) {
    hljs.registerLanguage(name, def);
}

// Serialize the state needed for the browser — we rebuild the core API with only
// the registered grammars so the bundle is lean.
const registeredLangs = {};
for (const [name] of LANGS) {
    try {
        const def = hljs.getLanguage(name);
        // Store the serializable definition we can use to re-register
        registeredLangs[name] = def;
    } catch { /* skip */ }
}

// We'll embed the whole hljs module using a simple IIFE wrapper that reads from
// the Node.js resolved module and serialises it for browser use.
// The cleanest way: bundle the source directly using dynamic require resolution.

const fs = require('fs');
const path = require('path');

// Read the core source
const coreSrc = fs.readFileSync(
    path.join(__dirname, '../node_modules/highlight.js/lib/core.js'),
    'utf8'
);

// Read each language source
const langParts = [];
const LANG_FILES = [
    ['javascript', 'javascript'],
    ['typescript', 'typescript'],
    ['python',     'python'],
    ['rust',       'rust'],
    ['go',         'go'],
    ['java',       'java'],
    ['kotlin',     'kotlin'],
    ['swift',      'swift'],
    ['csharp',     'csharp'],
    ['cpp',        'cpp'],
    ['c',          'c'],
    ['php',        'php'],
    ['ruby',       'ruby'],
    ['bash',       'bash'],
    ['shell',      'shell'],
    ['css',        'css'],
    ['scss',       'scss'],
    ['xml',        'xml'],
    ['json',       'json'],
    ['yaml',       'yaml'],
    ['ini',        'ini'],
    ['sql',        'sql'],
    ['markdown',   'markdown'],
    ['dockerfile', 'dockerfile'],
    ['makefile',   'makefile'],
    ['diff',       'diff'],
    ['plaintext',  'plaintext'],
];

const langSrcs = [];
for (const [alias, file] of LANG_FILES) {
    const langPath = path.join(__dirname, `../node_modules/highlight.js/lib/languages/${file}.js`);
    if (!fs.existsSync(langPath)) { continue; }
    const src = fs.readFileSync(langPath, 'utf8');
    langSrcs.push({ alias, file, src });
}

// Build a self-contained browser bundle using a UMD/IIFE wrapper.
// We convert each CommonJS module to a function that receives a minimal "module"
// shim, then extract the export.

const bundle = `
/* OllamaPilot — vendored highlight.js bundle (offline, no CDN) */
/* Generated by scripts/vendor-hljs.js — do not edit manually  */
(function(window) {
  'use strict';

  /* ── CommonJS shim ──────────────────────────────────────────────────────── */
  function _require_mod(factory) {
    const mod = { exports: {} };
    factory(mod, mod.exports);
    return mod.exports;
  }

  /* ── highlight.js core ──────────────────────────────────────────────────── */
  const hljs = _require_mod(function(module, exports) {
${coreSrc}
  });

  /* ── Languages ──────────────────────────────────────────────────────────── */
${langSrcs.map(({ alias, src }) => `
  hljs.registerLanguage('${alias}', _require_mod(function(module, exports) {
${src}
  }));`).join('\n')}

  /* Short aliases — wrap in a factory fn so registerLanguage is happy */
  function _alias(name) { return function(h) { return h.getLanguage(name) || {}; }; }
  ['html','xml'].forEach(function(n) { try { hljs.registerLanguage('html', _alias('xml')); } catch {} });
  try { hljs.registerLanguage('sh',   _alias('bash')); } catch {}
  try { hljs.registerLanguage('toml', _alias('ini'));  } catch {}
  try { hljs.registerLanguage('ts',   _alias('typescript')); } catch {}
  try { hljs.registerLanguage('js',   _alias('javascript')); } catch {}
  try { hljs.registerLanguage('py',   _alias('python')); } catch {}

  /* Expose globally */
  window.hljs = hljs;
})(typeof window !== 'undefined' ? window : globalThis);
`;

const outPath = path.join(__dirname, '../webview/vendor/highlight.bundle.js');
fs.writeFileSync(outPath, bundle, 'utf8');

const sizeKb = Math.round(fs.statSync(outPath).size / 1024);
console.log(`✓ highlight.bundle.js written — ${sizeKb} KB`);
